slug: itpcp.pgph.py.easter_formula
version: 1.0.1
title: Easter Formula
description: 'In this exercise you will calculate the date of Easter Sunday using
  the Gaussian

  Easter formula. You will practice arithmetic operators (modulo, integer division),

  user input with input and formatted output with f-strings.

  '
language: de
license: MIT
authors:
- name: Patrick Lainer
  email: patrick.lainer@tugraz.at
  affiliation: TU Graz
- name: Michael Meierhofer
  email: mike@trigonal.at
  affiliation: TU Graz
maintainers:
- name: Christopher Albert
  email: albert@tugraz.at
  affiliation: TU Graz
links:
- description: Wikipedia - Date of Easter
  url: https://en.wikipedia.org/wiki/Date_of_Easter
supportingMaterial:
- description: input
  url: https://docs.python.org/3/library/functions.html#input
- description: int
  url: https://docs.python.org/3/library/functions.html#int
- description: print
  url: https://docs.python.org/3/library/functions.html#print
- description: python-fstrings
  url: https://docs.python.org/3/tutorial/inputoutput.html
keywords:
- python
