slug: itpcp.pgph.py.pi_random
version: 1.0.0
title: Pi - Just a Coincidence?
description: This exercise demonstrates the Monte Carlo method for calculating Pi.
  By randomly distributing points in a square and counting the points inside an inscribed
  circle, Pi is approximated. The convergence is improved through repeated experiments
  and averaging.
language: de
license: MIT
authors:
- name: Patrick Lainer
  email: patrick.lainer@tugraz.at
  affiliation: TU Graz
- name: Michael Meierhofer
  email: mike@trigonal.at
  affiliation: TU Graz
maintainers:
- name: Christopher Albert
  email: albert@tugraz.at
  affiliation: TU Graz
links:
- description: Wikipedia - Monte Carlo method
  url: https://en.wikipedia.org/wiki/Monte_Carlo_method
- description: Wikipedia - Pi
  url: https://en.wikipedia.org/wiki/Pi
supportingMaterial:
- description: NumPy random.rand
  url: https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
- description: NumPy cumsum
  url: https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html
- description: Matplotlib pyplot
  url: https://matplotlib.org/stable/api/pyplot_summary.html
keywords:
- python
