slug: itpcp.pgph.py.vector_field
version: 1.0.0
title: Vector Fields and Eigenvectors
description: This exercise visualizes vector fields and eigenvectors using matplotlib.
  A gradient field is generated and transformed by a matrix. The eigenvectors of the
  transformation matrix are calculated and displayed graphically.
language: de
license: MIT
authors:
- name: Martin Tritthart
  affiliation: TU Graz
- name: Michael Meierhofer
  email: mike@trigonal.at
  affiliation: TU Graz
- name: Patrick Lainer
  email: patrick.lainer@tugraz.at
  affiliation: TU Graz
maintainers:
- name: Christopher Albert
  email: albert@tugraz.at
  affiliation: TU Graz
links:
- description: Wikipedia - Eigenvalues and eigenvectors
  url: https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors
- description: Wikipedia - Vector field
  url: https://en.wikipedia.org/wiki/Vector_field
supportingMaterial:
- description: Matplotlib quiver
  url: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html
- description: NumPy meshgrid
  url: https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html
- description: NumPy linalg.eig
  url: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html
keywords:
- python
