slug: itpcp.pgph.py.uncertainties
version: 1.0.0
title: 'Error Propagation: Linear vs Monte Carlo'
description: This exercise compares linear error propagation with the Monte Carlo
  method. The Python package uncertainties is used to propagate measurement uncertainties.
  The limits of the linear approximation for nonlinear functions are visualized through
  histograms.
language: de
license: MIT
authors:
- name: Christopher Albert
  email: albert@tugraz.at
  affiliation: TU Graz
- name: Michael Meierhofer
  email: mike@trigonal.at
  affiliation: TU Graz
maintainers:
- name: Christopher Albert
  email: albert@tugraz.at
  affiliation: TU Graz
links:
- description: Wikipedia - Propagation of uncertainty
  url: https://en.wikipedia.org/wiki/Propagation_of_uncertainty
- description: Wikipedia - Monte Carlo method
  url: https://en.wikipedia.org/wiki/Monte_Carlo_method
supportingMaterial:
- description: Python uncertainties Paket
  url: https://pythonhosted.org/uncertainties/
- description: NumPy random.default_rng
  url: https://numpy.org/doc/stable/reference/random/generator.html
- description: Python List Comprehension
  url: https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions
keywords:
- python
